### ISSUE TITLE
Not in Vocab Error When Replicating the result

### ISSUE THREAD

**Issue by AndyWeasley2004** [SirawitC/NLP-based-music-processing-for-composer-classification#1]
Run the notebook with the properly downloaded dataset, but encounter the following error when fitting the model

Not in vocab
Not in vocab
Not in vocab
Not in vocab
Not in vocab
Not in vocab
Not in vocab
Not in vocab
Not in vocab
Not in vocab
Not in vocab
Not in vocab
Not in vocab
Not in vocab
Not in vocab
Not in vocab
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
[<ipython-input-43-7dab09d31a37>](https://localhost:8080/#) in <cell line: 1>()
----> 1 KNN, RFC, Logis, Avg, SVM, MLP = Main("/content/drive/MyDrive/Composer Classification/replicate_final.txt","m",13000,5000,5,True,False)
      2 print("Avg:", Avg)
      3 print("F1-score of KNN:",KNN)
      4 print("F1-score of RFC:",RFC)
      5 print("F1-score of Logistic:",Logis)

2 frames
[<ipython-input-41-6437a1debb41>](https://localhost:8080/#) in Main(corpus, modelName, vocabSize, maxSenLength, window, Avg, cov)
      1 def Main(corpus, modelName, vocabSize, maxSenLength, window, Avg=False, cov=False):
      2   sentences = sentencePiece(corpus, modelName, vocabSize, maxSenLength)
----> 3   sentencesLst = Word2Vec(window, sentences, Avg, cov)
      4   data, label = createLabel(sentencesLst)
      5   sentence_w_label_100 = pd.DataFrame({"sentence": data, "label":label})

[<ipython-input-40-a541c0b834d7>](https://localhost:8080/#) in Word2Vec(Window, sentences, Avg, SD)
     11       return sentenceLstAvgwithCov
     12   elif(Avg and (not SD)):
---> 13       sentencesLstAvg = get_sentence_vec_avg(sentences,model)
     14       return sentencesLstAvg
     15   elif((not Avg) and SD):

[<ipython-input-16-3b0a1c56996b>](https://localhost:8080/#) in get_sentence_vec_avg(sentences, model)
      8       except:
      9         print("Not in vocab")
---> 10     l.append(temp/len(sentence))
     11   return l

UnboundLocalError: local variable 'temp' referenced before assignment

**Comment by AndyWeasley2004** [comment]
I have tried multiple times and "Not in Vocab" appears in every running.

**Comment by AndyWeasley2004** [comment]
For AVG only case, the program exit due to the unbound error, and for the SD only case, the following error is raised:
All content of the notebook is not modified except for the dataset path in my drive.
![image](https://github.com/SirawitC/NLP-based-music-processing-for-composer-classification/assets/110661816/6d7e1eb0-6262-42d3-895c-ff457379bc9d)

**Comment by SorawitChok** [comment]
Dear @AndyWeasley2004,

We appreciate your interest in our work and thank you for bringing this issue to our attention.

It appears that the issue you are currently encountering may be attributed to an incompatibility with the gensim package version. To address this, we kindly recommend using gensim version 3.8.3, rather than the latest version. You can install this specific version with the following command:

`!pip install gensim==3.8.3`

We believe that this adjustment should help resolve the problem you're facing.

Once again, we want to express our gratitude for your interest and your effort in reaching out.

Warm regards,

Sorawit & Sirawit

**Comment by AndyWeasley2004** [comment]
Dear Sorawit & Sirawit,

Thank you for your information. However, when I tried to install the 3.8.3 version of gensim on my Google Colab, the wheel building always failed. I'm wondering whether it is a Python version problem as the colab only provides Python 3.10.12, which is a pretty new version.
<img width="826" alt="Screenshot 2023-10-16 at 2 42 47 PM" src="https://github.com/SirawitC/NLP-based-music-processing-for-composer-classification/assets/110661816/0a7e31ea-f859-4845-ab0d-c4fbf2932103">
<img width="1107" alt="Screenshot 2023-10-16 at 2 45 12 PM" src="https://github.com/SirawitC/NLP-based-music-processing-for-composer-classification/assets/110661816/bc250a73-dcfb-4184-8f61-f4efa1b793ff">

Thank you again for your assistance!

Sincerely,
Mingyang

**Comment by SorawitChok** [comment]
Dear @AndyWeasley2004,

We have identified an alternative approach to address the issue you encountered. This solution enables you to use the latest gensim version with some code modifications. Please consider implementing the following code instead:

**get_sentence_vec_avg_with_cov2 function:**
```
def get_sentence_vec_avg_with_cov2(sentences,model):
  l = []
  cov = []
  for sentence in sentences:
    for word in sentence:
      try:
        temp = np.zeros(len(model.wv[word])) # Updated to use 'model.wv' in newer gensim versions
        temp += model.wv[word] # Updated to use 'model.wv' in newer gensim versions
        cov.append(model.wv[word]) # Updated to use 'model.wv' in newer gensim versions
      except:
        print("Not in vocab")
    data = np.array(cov)
    sd = np.std(data,axis=0)
    z = temp/len(sentence)
    z = z.tolist()
    z += sd.tolist()
    z = np.array(z)
    l.append(z)
  return l
```
**get_sentence_vec_SD_only function:**
```
def get_sentence_vec_SD_only(sentences,model):
  l = []
  cov = []
  for sentence in sentences:
    for word in sentence:
      try:
        cov.append(model.wv[word]) # Updated to use 'model.wv' in newer gensim versions
      except:
        print("Not in vocab")
    data = np.array(cov)
    sd = np.std(data,axis=0)
    z = sd.tolist()
    z = np.array(z)
    l.append(z)
  return l
```
**get_sentence_vec_avg function:**
```
def get_sentence_vec_avg(sentences,model):
  l = []
  for sentence in sentences:
    for word in sentence:
      try:
        temp = np.zeros(len(model.wv[word])) # Updated to use 'model.wv' in newer gensim versions
        temp += model.wv[word] # Updated to use 'model.wv' in newer gensim versions
      except:
        print("Not in vocab")
    l.append(temp/len(sentence))
  return l
```

P.S. We have also made the necessary modifications to the source code to accommodate these changes. Your feedback has been integral in improving the project, and we appreciate your valuable input.

Warm regards,
Sorawit & Sirawit
